name: Get-Stock-Data-Customizable

on:
  push:
    paths:
      - '**.py' # 仅在修改代码时触发，避免无谓运行
  workflow_dispatch:
    inputs:
      stock_code:
        description: '请输入股票代码 (例如: sh600900, sz000001)'
        required: true
        default: 'sh600900'
      start_date:
        description: '请输入起始日期 (格式: YYYY-MM-DD)'
        required: true
        default: '2024-09-18'
      # 【新增】周期选择下拉菜单
      frequency:
        description: '请选择K线周期'
        required: true
        default: '1d'
        type: choice
        options:
          - '1d'
          - '1w'
          - '1m'
          - '5m'
          - '15m'
          - '30m'
          - '60m'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 运行我的股票脚本
        # 这里通过环境变量将输入参数传递给 Python
        env:
          STOCK_CODE: ${{ github.event.inputs.stock_code }}
          START_DATE: ${{ github.event.inputs.start_date }}
          # 【新增】将用户选择的周期传递给环境变量项
          FREQUENCY: ${{ github.event.inputs.frequency }}
        run: python main.py

      - name: 保存结果到云端
        uses: actions/upload-artifact@v4
        with:
          name: stock-data-result
          path: "*.csv"
